version: '2'
services:
    web:
        build:
            context: ./../
            dockerfile: docker/web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - ${HTTP_EXPOSED_PORT}:80
    app:
        build:
            context: ./../
            dockerfile: docker/app.dockerfile
        working_dir: /var/www/
        volumes:
            - ./../:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"    
    mysql:
        build:
            context: ./
            dockerfile: mysql.dockerfile
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
            - "MYSQL_ROOT_PASSWORD=${MYSL_ROOT_PASSWORD}"
        ports:
            - "${DATABASE_EXPOSED_PORT}:3306"
volumes:
    dbdata:
