#!/bin/bash

echo -e "\nDownloading composer..."
echo "-----------------------------------------------"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
( cd .. ; php ./docker/composer.phar install )
echo -e "\nCleaning up..."
echo "-----------------------------------------------"
rm composer.phar

echo -e "\nSetting up containers..."
echo "-----------------------------------------------"
sudo docker-compose build
sudo docker-compose up -d

echo -e "\nSetting up migrations..."
echo "-----------------------------------------------"
sudo docker-compose exec app php artisan migrate --seed
